server:
  port: 7070
eureka:
    client:
     enabled: false 
     
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2      
   
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    
    
   
  
